# Generated by Django 3.1.8 on 2021-06-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50)),
                ('definition', models.CharField(max_length=300)),
                ('collection_id', models.IntegerField()),
                ('flash_card_id', models.IntegerField()),
            ],
        ),
    ]
