# Generated by Django 3.1.8 on 2021-06-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='flash_card_id',
        ),
    ]
