# Generated by Django 3.1.8 on 2021-06-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0002_remove_flashcard_flash_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='collection_id',
            field=models.CharField(max_length=50),
        ),
    ]
