# Generated by Django 3.1.8 on 2021-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0003_auto_20210603_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='collection_id',
            field=models.IntegerField(),
        ),
    ]
