# Generated by Django 3.1.8 on 2021-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0004_auto_20210603_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='collection_id',
            field=models.CharField(max_length=50),
        ),
    ]
