# Generated by Django 3.1.8 on 2021-06-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0005_auto_20210603_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='collection_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
